config/routes.rb
Forum::Application.routes.draw do
  resources :users
  resources :posts, only: [:create, :show]
  resources :comments, only: [:create]
  resources :topics do
    resources :posts, only: [:new]
  end
  resources :surveys, only: [:new, :create] do
    collection do
      get :results
    end
  end

  root to: "topics#index"
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  attr_accessible :body, :post_id#, :user_id

  # belongs_to :user
  belongs_to :post

  validates :body, presence: true, uniqueness: true
  validates :post_id, presence: true
  # validates :user_id, presence: true
end

app/models/post.rb
class Post < ActiveRecord::Base
  attr_accessible :body, :title, :topic_id

  belongs_to :topic
  has_many :comments

  validates :body, presence: true, length: { within: 10..2000 },
            uniqueness: true
  validates :title, presence: true
  validates :topic_id, presence: true
end

app/models/survey.rb
class Survey < ActiveRecord::Base
  attr_accessible :age, :fav_cat_meme, :favorite_celeb, :most_embarassing_moment

  validates :age, presence: true
  validates :fav_cat_meme, presence: true
  validates :favorite_celeb, presence: true
  validates :most_embarassing_moment, presence: true

  def self.most_pop_cat
    self
      .select("fav_cat_meme, COUNT(*) AS cat_popularity")
      .group(:fav_cat_meme)
      .order("cat_popularity DESC")
      .first
  end

  def self.most_pop_celeb
    self
      .select("favorite_celeb, COUNT(*) as celeb_popularity")
      .group(:favorite_celeb)
      .order("celeb_popularity DESC")
      .first
      .favorite_celeb
  end

  def self.random_moment
    self
      .select("most_embarassing_moment")
      .order("RANDOM()")
      .first
  end
end

app/models/topic.rb
class Topic < ActiveRecord::Base
  attr_accessible :description, :title

  has_many :posts

  validates :title, presence: true, length: { maximum: 15 }
  validates :description, length: { maximum: 1245 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery except: :create
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def create
    @comment = Comment.new(params[:comment])
    @post = Post.find(params[:comment][:post_id])

    if @comment.save
      respond_to do |format|
        format.html do
          flash[:success] = "Your comment has been added."
          redirect_to post_path(@post)
        end
        format.json { render json: { errors: [], comment: @comment } }
      end
    else
      respond_to do |format|
        format.html do
          flash[:error] = "Your post wasn't saved. Try again?"
          redirect_to post_path(@post)
        end
        format.json do render json: {
          errors: ["Your post wasn't saved. Try again?"],
          comment: @comment }
        end
      end
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  def new
    @post = Post.new
    @topic = Topic.find(params[:topic_id])
  end

  def create
    @post = Post.new(params[:post])
    @topic = Topic.find(@post.topic_id)

    if @post.save
      respond_to do |format|
        format.html do
          flash[:success] = "Your post has been saved!"
          redirect_to @post
        end
        format.json do
          render :json => { errors: [], post: @post }
        end
      end
    else
      respond_to do |format|
        format.html do
          flash[:error] = "Wrongzies..."
          render "new"
        end
        format.json do
          render :json => { errors: ["Wrongzies..."], post: @post }
        end
      end
    end
  end

  def show
    @post = Post.find(params[:id])
    @comment = Comment.new(post_id: @post.id)

    respond_to do |format|
      format.html
      format.json do render :json => { post: @post,
        comments: @post.comments }
      end
    end
  end
end

app/controllers/surveys_controller.rb
class SurveysController < ApplicationController

  def new
    @survey = Survey.new
  end

  def create
    @survey = Survey.new(params[:survey])

    if @survey.save
      flash[:success] = "Your survey has been submitted!"
      redirect_to results_surveys_path
    else
      flash[:error] = "Something went wrong"
      render 'new'
    end
  end

  def results
    @results = Survey.all
  end
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  def new
    @topic = Topic.new
  end

  def create
    @topic = Topic.new(params[:topic])

    if @topic.save
      respond_to do |format|
        format.html do
          flash[:success] = "Your topic has been created!"
          redirect_to @topic
        end
        format.json { render json: { errors: [], topic: @topic } }
      end
    else
      respond_to do |format|
        format.html do
          flash[:error] = "Something went wrong. Try again!"
          render "new"
        end
        format.json do render json: {
          errors: ["Something went wrong. Try again!"],
          topic: @topic }
        end
      end
    end
  end

  def show
    @topic = Topic.find(params[:id])

    respond_to do |format|
      format.html
      format.json { render json: @topic }
    end
  end

  def index
    @topics = Topic.all
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(params[:user])

    if @user.save
      flash[:success] = "Your profile has been created!"
      redirect_to @user
    else
      flash[:error] = "Try again?"
      render "new"
    end
  end

  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def full_title(page_name)
    base = "AnonyChats"
    if page_name.empty?
      base
    else
      "#{base} | #{page_name}"
    end
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/surveys_helper.rb
module SurveysHelper
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_header.html.erb
<div class="navbar navbar-fixed-top">
  <div class="container-fluid">
    <ul class="header">
      <li>
        <%= link_to(image_tag('cat.jpeg', :alt => "AnonyChat"), root_path,
          class: "brand") %>
      </li>
    </ul>

      <div class="nav pull-center">
          <h1>AnonyChat</h1>
      </div>

      <div class="navbar-form pull-right">
        <ul class="header">
          <li>
            <%= link_to "Take ze zurvey", new_survey_path,
                class: "btn btn-medium btn-danger" %>
          </li>

          <li>
            <%= link_to "Create a new topic", new_topic_path,
                class: "btn btn-medium btn-info" %>
          </li>
        </ul>
      </div>
    </ul>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield :page_name) %></title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

  <% flash.each do |key, value| %>
    <%= content_tag(:div, value, class: "alert alert-#{key}") %>
  <% end %>

  <div class="container">
    <%= render "layouts/header" %>
    <%= yield %>
  </div>

</body>
</html>

app/views/posts/_comment.html.erb
<h4><%= comment.body %></h4>
<p>Created <%= distance_of_time_in_words_to_now(comment.created_at)%> ago</p>

app/views/posts/new.html.erb
<h1>Add your post for <%= link_to @topic.title, topic_path(@topic) %> here!</h1>

<%= simple_form_for @post do |f| %>
  <%= f.hidden_field :topic_id, value: @topic.id %>

  <%= f.input :title %>

  <%= f.input :body %>

  <%= f.button :submit %>

<% end %>

app/views/posts/show.html.erb
<h1>Topic Board: <%= @post.topic.title %></h1>

<h2>Post: <%= @post.title %></h2>

<%= @post.body %>

<%= simple_form_for @comment do |f| %>

  <%= f.hidden_field :post_id %>

  <%= f.input :body, label: "Comment" %><br>

  <%= f.button :submit %>

<% end %>

<% @post.comments.each do |comment| %>
  <%= render partial: "comment", object: comment %>
<% end %>

app/views/shared/_post.html.erb
<h3><%= link_to post.title, post_path(post) %></h3>
<p>Created <%= distance_of_time_in_words_to_now(post.created_at)%> ago</p>
<p>Replies: <%= post.comments.count %></p> <!-- link to comments -->

app/views/surveys/new.html.erb
<h1>Welcome to our complex survey form thingy!</h1>

<%= simple_form_for @survey do |f| %>
  <%= f.input :favorite_celeb, collection: ["Reba McEntire", "Mandy Moore",
    "The Hulk", "Ned Ruggeri", "Prez Obamz", "Florence Welch"],
    prompt: "Optimal valentine?" %><br>

  <%= f.input :age, collection: 14..85 %>

  <%= f.input :fav_cat_meme, collection: [[image_tag("cat1.jpeg"), 1],
              [image_tag("cat2.jpeg"), 2], [image_tag("cat3.jpeg"), 3]],
              as: :radio_buttons %>

  <%= f.input :most_embarassing_moment,
              placeholder: "It's really 'embarrassing'" %>

  <%= f.button :submit %>


<% end %>

app/views/surveys/results.html.erb
<h1>Survey Results!</h1>

<h3>Average age of respondents:</h3>
<%= Survey.average('age') %>

<h3>Most popular cat meme:</h3>
<%= image_tag("cat#{Survey.most_pop_cat.fav_cat_meme}.jpeg",
                alt: "most popular cat") %>

<h3>Hottest Valentine:</h3>
<%= Survey.most_pop_celeb %>

<h3>Random most embarrassing moment</h3>
<%= Survey.random_moment.most_embarassing_moment %>

app/views/topics/index.html.erb
<h1>These are all of the topics:</h1>

  <% @topics.each do |t| %>

    <div class="topic">
      <%= link_to t.title, topic_path(t) %>
    </div>

  <% end %>

<br>

app/views/topics/new.html.erb
<h1>Create a new topic!</h1>

<%= simple_form_for @topic do |f| %>

  <%= f.input :title, placeholder: "name your topic board" %>

  <%= f.input :description,
              placeholder: "optional: what is this topic board about?" %>

  <%= f.button :submit %>

<% end %>

app/views/topics/show.html.erb
<h1>Topic board for: <%= @topic.title %></h1>

<%= link_to "Create a new Post", new_topic_post_path(@topic), class: "btn btn-medium" %>

<%= render partial: "shared/post", collection: @topic.posts %>